Sprint 1
Vosssable/middle.messenger.praktikum.yandex pull request #1
Opened 2024-12-11 18:47 UTC by Vosssable

2024-12-11 19:55 UTC, aromanovnik requested changes
Добрый день, Tema Amet!

Работа выполнена очень хорошо: Версия Node.js указана в проекте, структура файлов хорошо организована. Проект задеплоен на Netlify и работает без сбоев. Код чистый, структурированный и читаемый. Отличная работа!

Тем не менее, есть несколько замечаний, которые потребуют доработки. Более подробно о них написано в комментариях к коду.

**Что нужно исправить**:
* По заданию 1-го спринта каждому инпуту в формах проекта необходимо задать конкретный атрибут `name`, соответствующий требованиям. Это позволит избежать изменений в 3-м спринте при подключении к API. Убедитесь, что атрибуты `name` заданы корректно для всех инпутов в проекте.
* По правилам семантической разметки, на всех страницах весь основной контент следует помещать в тег `main`. Это улучшает доступность и структурированность страницы, так как помогает браузерам и скринридерам правильно интерпретировать и навигировать по содержимому. Подробнее: https://htmlacademy.ru/blog/html/semantics
* В соответствии с семантикой и пунктом 7 чеклиста, заголовки на странице должны быть обёрнуты в соответствующие теги уровней `h1…h6`. Это помогает соблюсти правильную иерархию заголовков, улучшает доступность для экранных читалок и оптимизирует SEO.
* По заданию требуется реализовать формы для настройки пользователя. На данный момент формы **для изменения аватара** и **для изменения пароля** отсутствуют. 
* Согласно чеклисту (пункт 7), меню навигации должно быть обернуто в тег `<nav>`. Это обеспечит правильную семантику HTML, улучшит доступность сайта для пользователей и корректную работу вспомогательных технологий.
* Список ссылок должен быть семантически правильным. Поскольку он визуально выглядит как список, для его разметки необходимо использовать теги `<ul>` и `<li>`. Это повысит доступность для пользователей с ограниченными возможностями и будет соответствовать стандартам семантической разметки.

**Что можно улучшить**:
* Поскольку интерфейс проекта русскоязычный, рекомендуется установить атрибут языка в корневом теге `<html lang="ru">`. Это предотвратит ситуации, когда устройства или браузеры могут неправильно определять язык страницы, предлагать перевод, либо автоматически изменять содержимое. Подробнее об одной из таких проблем: https://habr.com/ru/post/650907/
* Тег `script` с атрибутом `type="module"` лучше размещать внутри `head`, потому что модули загружаются асинхронно и не блокируют загрузку контента страницы.
* Все цвета лучше вынести в CSS-переменные, чтобы улучшить поддержку кода. Это позволяет мгновенно понять назначение цвета, избежать дублирования, а также облегчить изменения — достаточно подкорректировать цвет в одном месте, что повышает гибкость и масштабируемость стилей.
* В проекте некоторые файлы с кодом не заканчиваются переводом строки, что важно для соблюдения стандартов кодирования. Перевод строки в конце файла (`EOF`) предотвращает потенциальные проблемы при объединении файлов и улучшает читаемость в системах контроля версий, таких как Git. Чтобы автоматизировать это требование, настройте редактор кода и добавьте в `.editorconfig` параметр `insert_final_newline = true`. Подробная информация по настройке доступна на [editorconfig.org](https://editorconfig.org). 
* По семантике для подписи к полю формы предпочтительно использовать тег `<label>` вместо `<div>`. Это улучшает доступность для пользователей и корректную работу средств навигации по форме.
* Каждой картинке (тегу `img`) следует добавить информативный атрибут `alt` (**Не пустой**). Это важно не только для улучшения доступности сайта, но и для SEO. В случае ошибки загрузки изображения, в `alt` будет отображаться описание, и пользователи смогут понять, что изображение не удалось загрузить. Атрибут `alt` также необходим для пользователей с нарушениями зрения, так как специальные программы для чтения с экрана могут озвучивать текст в `alt`. Для дополнительной информации можно ознакомиться: https://habr.com/ru/articles/341810/
* **Можно лучше:** В package.json для скриптов `start`,` build` и `preview` указывать полный путь к `node_modules/.bin/vite` не обязательно. Бинарные файлы автоматически добавляются в PATH при выполнении команд через `npm run`. Можно упростить записи до:
```
"scripts": {
  "start": "vite",
  "build": "vite build",
  "preview": "vite preview"
}
```

Напоминаю, что работа может быть принята только после исправления всех критических замечаний **Надо исправить**.

Удачного рефакторинга кода.

2024-12-11 19:55 UTC, aromanovnik commented on index.html
> +<html lang="en">
**Можно лучше**: Поскольку интерфейс проекта русскоязычный, рекомендуется установить атрибут языка в корневом теге `<html lang="ru">`. Это предотвратит ситуации, когда устройства или браузеры могут неправильно определять язык страницы, предлагать перевод, либо автоматически изменять содержимое. Подробнее об одной из таких проблем: https://habr.com/ru/post/650907/

2024-12-11 19:55 UTC, aromanovnik commented on index.html
> +  <script type="module" src="/src/main.js"></script>
**Можно лучше**: Тег `script` с атрибутом `type="module"` лучше размещать внутри `head`, потому что модули загружаются асинхронно и не блокируют загрузку контента страницы.

2024-12-11 19:55 UTC, aromanovnik commented on src/utils/FormsAttrs.js
> +            input: true,
**Надо исправить**: По заданию 1-го спринта каждому инпуту в формах проекта необходимо задать конкретный атрибут `name`, соответствующий требованиям. Это позволит избежать изменений в 3-м спринте при подключении к API. Убедитесь, что атрибуты `name` заданы корректно для всех инпутов в проекте.

2024-12-11 19:55 UTC, aromanovnik commented on src/components/chat.pcss
> +    border-top: 1px solid #EAEAEA;
**Можно лучше**: Все цвета лучше вынести в CSS-переменные, чтобы улучшить поддержку кода. Это позволяет мгновенно понять назначение цвета, избежать дублирования, а также облегчить изменения — достаточно подкорректировать цвет в одном месте, что повышает гибкость и масштабируемость стилей.

2024-12-11 19:55 UTC, aromanovnik commented on src/pages/loginPage/loginPage.hbs
> +<div class="app">
**Надо исправить**: По правилам семантической разметки, на всех страницах весь основной контент следует помещать в тег `main`. Это улучшает доступность и структурированность страницы, так как помогает браузерам и скринридерам правильно интерпретировать и навигировать по содержимому. Подробнее: https://htmlacademy.ru/blog/html/semantics

2024-12-11 19:55 UTC, aromanovnik commented on src/pages/profilePage/index.js
> +export { default as profilePage } from './profilePage.hbs?raw';
**Можно лучше**: В проекте некоторые файлы с кодом не заканчиваются переводом строки, что важно для соблюдения стандартов кодирования. Перевод строки в конце файла (`EOF`) предотвращает потенциальные проблемы при объединении файлов и улучшает читаемость в системах контроля версий, таких как Git. Чтобы автоматизировать это требование, настройте редактор кода и добавьте в `.editorconfig` параметр `insert_final_newline = true`. Подробная информация по настройке доступна на [editorconfig.org](https://editorconfig.org).

2024-12-11 19:55 UTC, aromanovnik commented on src/components/formInput.js
> +        <div class="form__label"> {{ placeholder }}</div>
**Можно лучше**: По семантике для подписи к полю формы предпочтительно использовать тег `<label>` вместо `<div>`. Это улучшает доступность для пользователей и корректную работу средств навигации по форме.

2024-12-11 19:55 UTC, aromanovnik commented on src/pages/errorPage/errorPage.hbs
> +        <div class="error__code">{{ code }}</div>
**Надо исправить**: В соответствии с семантикой и пунктом 7 чеклиста, заголовки на странице должны быть обёрнуты в соответствующие теги уровней `h1…h6`. Это помогает соблюсти правильную иерархию заголовков, улучшает доступность для экранных читалок и оптимизирует SEO.

2024-12-11 19:55 UTC, aromanovnik commented on src/pages/profilePage/profilePage.hbs
> +            <div class="profile-avatar">
Надо исправить: По заданию требуется реализовать формы для настройки пользователя. На данный момент формы **для изменения аватара** и **для изменения пароля** отсутствуют. 

<img width="600" alt="Снимок экрана 2024-12-11 в 22 33 18" src="https://github.com/user-attachments/assets/e52d6897-e6df-477d-9708-adca59c663a8" />

2024-12-11 19:55 UTC, aromanovnik commented on src/components/customRoute.js
> + <div class="temp-custom-route">
**Надо исправить**: Согласно чеклисту (пункт 7), меню навигации должно быть обернуто в тег `<nav>`. Это обеспечит правильную семантику HTML, улучшит доступность сайта для пользователей и корректную работу вспомогательных технологий.

2024-12-11 19:55 UTC, aromanovnik commented on src/components/customRoute.js
> + {{#each routes}}
**Надо исправить**: Список ссылок должен быть семантически правильным. Поскольку он визуально выглядит как список, для его разметки необходимо использовать теги `<ul>` и `<li>`. Это повысит доступность для пользователей с ограниченными возможностями и будет соответствовать стандартам семантической разметки.

2024-12-11 19:55 UTC, aromanovnik commented on src/pages/profilePage/profilePage.hbs
> +                <img src="/avatarNoPhoto.svg" alt="">
**Можно лучше**: Каждой картинке (тегу `img`) следует добавить информативный атрибут `alt` (**Не пустой**). Это важно не только для улучшения доступности сайта, но и для SEO. В случае ошибки загрузки изображения, в `alt` будет отображаться описание, и пользователи смогут понять, что изображение не удалось загрузить. Атрибут `alt` также необходим для пользователей с нарушениями зрения, так как специальные программы для чтения с экрана могут озвучивать текст в `alt`. Для дополнительной информации можно ознакомиться: https://habr.com/ru/articles/341810/

2024-12-11 19:55 UTC, aromanovnik commented on package.json
> +  "scripts": {
**Можно лучше:** В package.json для скриптов `start`,` build` и `preview` указывать полный путь к `node_modules/.bin/vite` не обязательно. Бинарные файлы автоматически добавляются в PATH при выполнении команд через `npm run`. Можно упростить записи до:
```
"scripts": {
  "start": "vite",
  "build": "vite build",
  "preview": "vite preview"
}
```

2024-12-12 19:22 UTC, Vosssable commented on index.html
> +<html lang="en">
Сделано!

2024-12-12 19:22 UTC, Vosssable commented on index.html
> +  <script type="module" src="/src/main.js"></script>
Сделано!

2024-12-12 19:23 UTC, Vosssable commented on src/utils/FormsAttrs.js
> +            input: true,
Исправлено. Так как id = name, то добавил в шаблоны соответствующее присвоение

2024-12-12 19:24 UTC, Vosssable commented on src/components/chat.pcss
> +    border-top: 1px solid #EAEAEA;
Почти все вынес, остальные пока не вижу смысла (как появятся снова, то непременно их внесу)

2024-12-12 19:24 UTC, Vosssable commented on src/pages/loginPage/loginPage.hbs
> +<div class="app">
Заменил на main

2024-12-12 19:24 UTC, Vosssable commented on src/pages/profilePage/profilePage.hbs
> +            <div class="profile-avatar">
Готово! Еще и со стилями подманил

2024-12-12 19:24 UTC, Vosssable commented on src/components/customRoute.js
> + <div class="temp-custom-route">
Сделано

2024-12-12 19:24 UTC, Vosssable commented on src/components/customRoute.js
> + {{#each routes}}
Исправлено

2024-12-12 19:25 UTC, Vosssable commented on src/pages/profilePage/profilePage.hbs
> +                <img src="/avatarNoPhoto.svg" alt="">
Добавил описания

2024-12-12 19:25 UTC, Vosssable commented on package.json
> +  "scripts": {
Сделано

2024-12-12 20:56 UTC, aromanovnik requested changes
Добрый день, Tema Amet!

Вы проделали большую работу, почти все замечания исправлены. Осталось устранить **одно** критическое замечание из первой итерации, и проект будет полностью соответствовать требованиям. Уверен, у вас все получится!

**Надо исправить**: По требованиям задания, должен быть инпут для выбора аватарки, с атрибутом `name`, равным 'avatar' https://disk.yandex.ru/i/ibV201nTqy0SkQ.

Удачного рефакторинга кода.

2024-12-12 20:56 UTC, aromanovnik commented on src/components/form.js
> +                <input type="file" id="upload_button__upload_form" hidden="hidden" name={{value}}>
**Надо исправить**: По требованиям задания, должен быть инпут для выбора аватарки, с атрибутом `name`, равным 'avatar'.

<img width="1215" alt="Снимок экрана 2024-12-12 в 23 45 29" src="https://github.com/user-attachments/assets/ba11c1ab-bede-42df-a4b6-9e43fd1b61bf" />

2024-12-12 21:06 UTC, Vosssable commented on src/components/form.js
> +                <input type="file" id="upload_button__upload_form" hidden="hidden" name={{value}}>
Увидел. В атрибутах передал value к кнопке, а не к инпуту...
Уно моменто)

2025-02-09 19:48 UTC, merged